/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description 项目卡片列表
         */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project
         * @description 项目详情
         */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Match
         * @description 提交需求 → 匹配 Team
         */
        post: operations["match_api_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Project
         * @description 确认 Team 成员
         */
        post: operations["confirm_project_api_projects__project_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ConfirmRequest */
        ConfirmRequest: {
            /**
             * Confirmedroles
             * @description 客户确认的角色列表
             * @example [
             *       {
             *         "photographerId": "citizen_018",
             *         "role": "photographer",
             *         "source": "platform"
             *       }
             *     ]
             */
            confirmedRoles: {
                [key: string]: unknown;
            }[];
            /**
             * Note
             * @description 客户备注
             */
            note?: string | null;
        };
        /** ConfirmResult */
        ConfirmResult: {
            /** Projectid */
            projectId: string;
            /** Status */
            status: string;
            /**
             * Confirmed
             * @default []
             */
            confirmed: string[];
            /**
             * Pending
             * @default []
             */
            pending: string[];
            /**
             * Nextstep
             * @default
             */
            nextStep: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MatchRequest */
        MatchRequest: {
            /**
             * Scene
             * @description 活动场景描述
             * @example AI产品发布会
             */
            scene: string;
            /**
             * Budget
             * @description 预算（元）
             * @example 5000
             */
            budget: number;
            /**
             * Location
             * @default 上海
             * @example 上海
             */
            location: string;
            /**
             * Roles
             * @description 需要的角色
             * @default [
             *       "photographer"
             *     ]
             * @example [
             *       "photographer",
             *       "editor"
             *     ]
             */
            roles: string[];
            /**
             * Customroles
             * @description 客户自备的角色
             * @default []
             * @example [
             *       "designer"
             *     ]
             */
            customRoles: string[];
        };
        /** MatchResponse */
        MatchResponse: {
            human: components["schemas"]["MatchResult"];
            /**
             * Agent
             * @default {}
             */
            agent: {
                [key: string]: unknown;
            };
        };
        /** MatchResult */
        MatchResult: {
            /** Projectid */
            projectId: string;
            /** Tier */
            tier: string;
            /** Recommendedteam */
            recommendedTeam: components["schemas"]["TeamSlot"][];
            /**
             * Alternativeoptions
             * @default {}
             */
            alternativeOptions: {
                [key: string]: components["schemas"]["TeamSlot"][];
            };
            /** Summary */
            summary: string;
        };
        /** PhotographerInfo */
        PhotographerInfo: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Tier */
            tier: string;
            /** Score */
            score: number;
            /** Skills */
            skills: string[];
            /** Completedtasks */
            completedTasks: number;
            /** Avgrating */
            avgRating: number;
        };
        /** ProjectCard */
        ProjectCard: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /**
             * Tier
             * @default pool
             */
            tier: string;
            /**
             * Budget
             * @default 0
             */
            budget: number;
            /**
             * Location
             * @default 上海
             */
            location: string;
            /** Team */
            team: components["schemas"]["TeamSlotSummary"][];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ProjectDetail */
        ProjectDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /**
             * Clientname
             * @default
             */
            clientName: string;
            /**
             * Requirement
             * @default
             */
            requirement: string;
            /**
             * Location
             * @default
             */
            location: string;
            /**
             * Budget
             * @default 0
             */
            budget: number;
            /**
             * Status
             * @default matching
             */
            status: string;
            /**
             * Tier
             * @default pool
             */
            tier: string;
            /**
             * Team
             * @default []
             */
            team: components["schemas"]["TeamSlot"][];
            /**
             * Timeline
             * @default []
             */
            timeline: components["schemas"]["TimelineEntry"][];
        };
        /** ProjectDetailResponse */
        ProjectDetailResponse: {
            human: components["schemas"]["ProjectDetail"];
            /**
             * Agent
             * @default {}
             */
            agent: {
                [key: string]: unknown;
            };
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Human */
            human: components["schemas"]["ProjectCard"][];
            /**
             * Agent
             * @default []
             */
            agent: {
                [key: string]: unknown;
            }[];
        };
        /** TeamSlot */
        TeamSlot: {
            /** Role */
            role: string;
            /**
             * Status
             * @default matched
             */
            status: string;
            photographer?: components["schemas"]["PhotographerInfo"] | null;
            /**
             * Source
             * @default platform
             */
            source: string;
        };
        /** TeamSlotSummary */
        TeamSlotSummary: {
            /** Role */
            role: string;
            /** Status */
            status: string;
            /** Assignee */
            assignee?: string | null;
        };
        /** TimelineEntry */
        TimelineEntry: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Event */
            event: string;
            /** By */
            by: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_projects_api_projects_get: {
        parameters: {
            query?: {
                role?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: {
                role?: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_api_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_project_api_projects__project_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
